apiVersion: v1
kind: Service
metadata:
  name: yaya-service
  labels:
    app: yaya-devops-project
spec:
  selector:
    app: yaya-devops-project
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200

